from .attendance import Attendance
from .driver import Driver
from .email_verification import EmailVerificationToken
from .fuel_record import FuelRecord
from .gps_tracking import GPSTracking
from .leave_request import LeaveRequest
from .maintenance import Maintenance
from .notification import Notification
from .shipment import Shipment
from .trip import Trip
from .user import User
from .vehicle import Vehicle
