"""initial schema

Revision ID: 1b1bf1409ffc
Revises: 
Create Date: 2026-07-23 20:21:13.611585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1bf1409ffc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('role', sa.Enum('Admin', 'FleetManager', 'Driver', 'Dispatcher', name='roleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    op.create_table('drivers',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('license_number')
    )

    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=20), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('assigned_driver', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['assigned_driver'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('registration_number')
    )

    op.create_table('attendance',
    sa.Column('attendance_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('attendance_id')
    )

    op.create_table('fuel_records',
    sa.Column('fuel_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('fuel_amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fuel_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mileage', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('refill_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('fuel_id')
    )

    op.create_table('gps_tracking',
    sa.Column('tracking_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('speed', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('recorded_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('tracking_id')
    )

    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )

    op.create_table('vehicle_maintenance',
    sa.Column('maintenance_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('maintenance_type', sa.String(length=50), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('maintenance_id')
    )

    op.create_table('shipments',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('tracking_number', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('shipment_weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('shipment_id'),
    sa.UniqueConstraint('tracking_number')
    )

    op.create_table('trips',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.Column('start_location', sa.String(length=100), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('shipments')
    op.drop_table('vehicle_maintenance')
    op.drop_table('notifications')
    op.drop_table('gps_tracking')
    op.drop_table('fuel_records')
    op.drop_table('attendance')
    op.drop_table('vehicles')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

