"""initial_schema

Revision ID: b1159da78ded
Revises: 
Create Date: 2026-07-24 10:41:21.734020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1159da78ded'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('role', postgresql.ENUM('Admin', 'FleetManager', 'Driver', 'Dispatcher', name='user_roles'), server_default='Driver', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('drivers',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('driver_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id'),
    sa.UniqueConstraint('notification_id')
    )
    op.create_table('attendance',
    sa.Column('attendance_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id'),
    sa.UniqueConstraint('attendance_id')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('assigned_driver', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_driver'], ['drivers.driver_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_table('fuel_records',
    sa.Column('fuel_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fuel_id'),
    sa.UniqueConstraint('fuel_id')
    )
    op.create_table('gps_tracking',
    sa.Column('tracking_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tracking_id'),
    sa.UniqueConstraint('tracking_id')
    )
    op.create_table('shipments',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('shipment_id'),
    sa.UniqueConstraint('shipment_id')
    )
    op.create_table('vehicle_maintenance',
    sa.Column('maintenance_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('maintenance_id'),
    sa.UniqueConstraint('maintenance_id')
    )
    op.create_table('trips',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('shipment_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('trip_id'),
    sa.UniqueConstraint('trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('vehicle_maintenance')
    op.drop_table('shipments')
    op.drop_table('gps_tracking')
    op.drop_table('fuel_records')
    op.drop_table('vehicles')
    op.drop_table('attendance')
    op.drop_table('notifications')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
